name = "signet-admin-panel"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

routes = [
  { pattern = "admin.signet.wenonly.cn", custom_domain = true }
]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_SERVER_URI = "https://signet.wenonly.cn"
NEXT_PUBLIC_CLIENT_ID = "FA4da496a346A0309A30b8d161F7732b2d702deaf8D0CC0Fddeb93764afea6BA"
NEXT_PUBLIC_SUPPORTED_LOCALES = "zh,en"
SERVER_CLIENT_ID = "fb5A64672869d53f486A88BBd112DF79f30E74cfA8893e2743AFEC75f04AA760"

[observability.logs]
enabled = true